<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="Our_FYPJ2019.Chat" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">

        <% foreach (var item in itemList) { %>
        <div class="row">
            <div class="col-sm-4">
                <div class="card mb-3" >
                    <img class="card-img-top" src="<%=item.image1 %>" alt="Card image cap" style="width:50%;height:20%">
                    <div class="card-body">
                        <h5 class="card-title"><%=item.itemname %></h5>                  
                    </div>
                </div>
            </div>
           
        </div>
        <% } %>

        <%--<form id ="form1" runat="server">--%>
            <asp:ScriptManager EnablePartialRendering="true" ID="ScriptManager1" runat="server"></asp:ScriptManager>
            <div>
            
                
            <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">

                <ContentTemplate>
                    
                    <asp:TextBox ID="message" runat="server"></asp:TextBox>
                    <asp:Button ID="sendmessage" runat="server" Text="send"/>
                    
                    <input type="hidden" id="displayname" value="<%= buyer %>" />
                    
                </ContentTemplate>
            </asp:UpdatePanel>

            <!-- dISPLAY -->   
            <ul id="discussion">
                <% if (chatList != null) {  %>
                    <% foreach (var item in chatList) { %>
                        <li><strong><%=item.buyer %> : </strong></li> <%= item.msg %>
                    <% }  %>
                <% } else { %>
                    <li><strong>No chat</strong></li>
                <% }  %>
            </ul>
                   
               
            <%--<asp:UpdatePanel ID="UpdatePanel2" runat="server" UpdateMode="Conditional">
                <ContentTemplate>
                    <asp:Label ID="Label2" runat="server" ForeColor="red" />
                </ContentTemplate>
                <Triggers>
                    <asp:AsyncPostBackTrigger ControlID="Button1" EventName="Click" />
                </Triggers>
            </asp:UpdatePanel>--%>

                
            </div>
        <%--</form>--%>
        
        <%--<input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" class="btn btn-success"/>--%>
        
    </div>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.3.1.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        

        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (<%= buyer %>, message) {
                // Html encode display name and message. 
                console.log("appended");
                var encodedName = $('<div />').text(<%= buyer %>).html();
                var encodedMsg = $('<div />').text(message).html();

                // Add the message to the page. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };

            // Get the user name and store it to prepend to messages.
            //$('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.  
            $('#<%= message.ClientID %>').focus();

            // start connection
            $.connection.hub.start().done(function () {
                $('#<%=sendmessage.ClientID %>').click(function() {
                    // Call the Send method on the hub. 
                    console.log("CLicked");

                    var chatmsg = $.trim($('#<%=message.ClientID %>').val());

                    if (msg != "") {
                        $.ajax({  
                            type: "POST",  
                            dataType: "json",  
                            contentType: "application/json; charset=utf-8",  
                            url: "chat.aspx?item=<%= itemid %>&item=<%= item %>&buyer=<%=buyer%>&seller=<%=seller%>",
                            data: "{'chatmsg':'" + chatmsg + "' , 'buyer':'" + <%=buyer%> + "' , 'seller':'" + <%=seller%> + "' , 'itemid':'" + <%=itemid%> + "' , 'item':'" + <%=item%> + "' , 'date':'" + <%=date%> + "' , 'time':'" + <%=time%> + "' }",  
                            success: function (data) {  
                       
                                $('#message').val();  
                                console.log("Sucessfully pushed")
  
                            },  
                            Error: function (data) {  
                      
                                console.log("Not successful");
                            }  
                        });  
                    }

                    chat.server.send($('#displayname').val(), $('#<%=message.ClientID%>').val());
                    // Clear text box and reset focus for next comment. 
                    $('#<%=message.ClientID%>').val('').focus();
                });
            });

        });
    </script>
</asp:Content>
