<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="signalrchattest.aspx.cs" Inherits="Our_FYPJ2019.signalrchattest" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        
        <asp:TextBox ID="message" runat="server"></asp:TextBox>
        <%--<input type="text" id="message" />--%>
        <asp:Button ID="sendmessage" runat="server" Text="Send" OnClick="sendmessage_Click" />
        <%--<input type="button" id="sendmessage" value="Send" />--%>
        <input type="hidden" id="displayname" runat="server"/>
        <ul id="discussion">
        </ul>
        
    </div>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.3.1.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 

    <script type="text/javascript">
        $(function () {

            // Declare a proxy to reference the hub. (ChatHub.cs)
            var chat = $.connection.chatHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = "<%= username %>";
                //var encodedName = $('<div />').text(name).html();               
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };

            // Get the user name and store it to prepend to messages.
            <%--$('#<%= displayname.ClientID %>').val(prompt('Enter your name:', ''));--%>

            // Set initial focus to message input box.  
            $('#<%= message.ClientID %>').focus();

            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#<%= sendmessage.ClientID %>').click(function () {

                    // Call the Send method on the hub. 
                    chat.server.send("<%= username %>", $('#<%= message.ClientID %>').val());
                    <%--chat.server.send($('#<%= displayname.ClientID %>').val(), $('#<%= message.ClientID %>').val());--%>

                    // Clear text box and reset focus for next comment. 
                    $('#<%= message.ClientID %>').val('').focus();

                });
            });
        });
    </script>
</asp:Content>
